defaults: &defaults
  working_directory: ~/app
  docker:
    - image: "circleci/golang:1.11"

version: 2
jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: run build
          command: |
            go build -v
      - run:
          name: run tests
          command: |
            go fmt ./...
            go vet ./...
            go test -v ./...

  deploy:
    <<: *defaults
    steps:
      - checkout
      - run: go get -u github.com/mitchellh/gox
      - run: go get -u github.com/tcnksm/ghr
      - run: go get -u github.com/stevenmatthewt/semantics
      - run:
          name: cross compile
          command: |
            gox -os="linux" -arch="amd64" -output="dist/spottyci_{{.OS}}_{{.Arch}}"
            cd dist/ && gzip *
      - add_ssh_keys:
      - run:
          name: create release
          command: |
            tag=$(semantics --output-tag)
            if [ "$tag" ]; then
              ghr -t $GITHUB_TOKEN -u $CIRCLE_PROJECT_USERNAME -r $CIRCLE_PROJECT_REPONAME --replace $tag dist/
            else
              echo "The commit message(s) did not indicate a major/minor/patch version."
            fi

workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
